- GB: fix backup_db to exit with a non-zero code, so when dbcomp fails the failure is caught by doone script

diff --git a/service/backup_db b/service/backup_db
--- a/service/backup_db
+++ b/service/backup_db
@@ -88,6 +88,7 @@ set -euxo pipefail
 : Optionally compare the restored test database with the backed up live db
 : ========================================================================
 :
+	DBCOMP_FAILED=
 	if [[  $OPTIONS =~ "V" ]]; then
 
 		if dbcomp $LIVE_EXO_DATA $TEST_EXO_DATA {S}; then
@@ -106,9 +107,11 @@ set -euxo pipefail
                 fi
         else
             :
-            : Flag fail - differences found
-            : =============================
+            : DBCOMP FAILED - differences found
+            : =================================
             :
+				# Dont exit 1 yet, in case dbdelete or service restart is required
+				DBCOMP_FAILED=1
 		fi
 	fi
 
@@ -127,6 +130,18 @@ set -euxo pipefail
 :
 	if [ ${RESTART_REQUIRED:-N} = Y ]; then
 		./service ${LIVE_EXO_DATA} start test
+	fi
+
+:
+: Check for dbcomp failure
+: ========================
+:
+	if [ "$DBCOMP_FAILED" ]; then
+		:
+		: Finished backup_db $1 in $(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds.
+		: ======================================================
+		# Caught exit code by doone
+		exit 1
 	fi
 
 :
