+ SB: Add service fix.foreign.dbname.sh and restore_db to use it instead of its old code. The new script can also fix the foreign dbname after copying a _test db to live.

diff --git a/service/restore_db b/service/restore_db
--- a/service/restore_db
+++ b/service/restore_db
@@ -86,76 +86,80 @@ PS4='+ [./restore_db ${LIVE_EXO_DATA:-${1-}} ${SECONDS}s] '
 	sudo -u postgres psql $TEST_EXO_DATA 2>&1 >/dev/null |\
 	(egrep -v '(^ERR.R:  function |^LINE [0-9]+: |^  |^HINT:  No function matches |^QUERY: |^CONTEXT: )' || true)
 :
+: Fix any foreign server dbname - _test suffix needs to match the restored dbname
+: ────────────────────────────────────────
+	./fix.foreign.dbname.sh $TEST_EXO_DATA
+:
 : Create all pgsql functions
 : ────────────────────────────────────────
 	EXO_DATA=$TEST_EXO_DATA dict2sql > /dev/null
-:
-: Reattach to foreign test database
-: ─────────────────────────────────────────────────────────────────────────────────
-: 'because pg_dump/restore preservers foreign table attachments'
-: 'leaving foreign tables in test databases access to update tables in live databases'
-: 'users of databases with foreign tables are restricted from updating but EXODUS is not!'
-:
-	#Ensure reattach is only done on test databases because
-	#sometimes we highjack restore_db to restore a backup into live database
-	if [[ $TEST_EXO_DATA =~ _test ]]; then
-
-		#Get foreign server name
-		FOREIGN_SERVER=`sudo -u postgres psql $TEST_EXO_DATA -t -c "\des+" | awk '{ print $1}'`
-		if [ "`echo $FOREIGN_SERVER | wc -l`" -gt 1 ]; then
-			: "ERROR: Reattaching foreign tables expects only one foreign server!"
-			exit 1
-		fi
-
-		if [ $FOREIGN_SERVER ]; then
-
-			# Redirect all the foreign tables to xxxxxx_test by changing the dbname of the "foreign server"
-			# Also remove the host so the connection are fast linux socket connections instead of tcp/ip
-			FOREIGN_TEST_DBNAME=${FOREIGN_SERVER}_test
-			if ! sudo -u postgres psql $TEST_EXO_DATA -t -c "ALTER SERVER $FOREIGN_SERVER OPTIONS (SET host '', SET dbname '$FOREIGN_TEST_DBNAME');"; then
-				: "ERROR: Problem changing foreign database to $FOREIGN_TEST_DBNAME"
-				exit 1
-			fi
-			#batesk_test=> \des+
-			#                                                         List of foreign servers
-			#  Name  | Owner  | Foreign-data wrapper | Access privileges | Type | Version |                 FDW options                  | Description 
-			#--------+--------+----------------------+-------------------+------+---------+----------------------------------------------+-------------
-			# batesd | exodus | postgres_fdw         |                   |      |         | (dbname 'batesd_test', host '', port '5432') | 
-
-#			#Get foreign table names before detaching
-#			FOREIGN_TABLES=`sudo -u postgres psql $TEST_EXO_DATA -t \
-#				-c "SELECT foreign_table_name FROM information_schema.foreign_tables;" \
-#				| tr '\n' ' '`
+#:
+#: Reattach to foreign test database
+#: ─────────────────────────────────────────────────────────────────────────────────
+#: 'because pg_dump/restore preservers foreign table attachments'
+#: 'leaving foreign tables in test databases access to update tables in live databases'
+#: 'users of databases with foreign tables are restricted from updating but EXODUS is not!'
+#:
+#	#Ensure reattach is only done on test databases because
+#	#sometimes we highjack restore_db to restore a backup into live database
+#	if [[ $TEST_EXO_DATA =~ _test ]]; then
 #
-#			sudo -u postgres psql -c "ALTER ROLE exodus WITH SUPERUSER;"
-#			#Remove foreign server/tables attachment to other live database:
-#			EXO_DATA=$TEST_EXO_DATA dbattach \{RRR\}
+#		#Get foreign server name
+#		FOREIGN_SERVER=`sudo -u postgres psql $TEST_EXO_DATA -t -c "\des+" | awk '{ print $1}'`
+#		if [ "`echo $FOREIGN_SERVER | wc -l`" -gt 1 ]; then
+#			: "ERROR: Reattaching foreign tables expects only one foreign server!"
+#			exit 1
+#		fi
 #
-#			#Reattach to other TEST database
-#			TIMEOUT=3600
-#			ELAPSED=0
-#			#Wait until source test database is finished being restore before dbattaching target/source test databases
-#			#otherwise dbcomp will fail because source db data not complete
-#			while ps -ef | egrep "backup_db $FOREIGN_SERVER" | grep -v 'grep'; do
-#				:
-#				: "Waiting for "$FOREIGN_SERVER"'s backup_db to finish before reattaching to "${FOREIGN_SERVER}_test
-#				:
-#				if [ $ELAPSED -ge $TIMEOUT ]; then
-#					: "TIMEOUT (60mins)"
-#					exit 1
-#				fi
-#				ELAPSED=$((ELAPSED + 60))
-#				sleep 60
-#			done
+#		if [ $FOREIGN_SERVER ]; then
 #
-#			#Reattach to source's TEST database
-#			EXO_DATA=$TEST_EXO_DATA dbattach ${FOREIGN_SERVER}_test $FOREIGN_TABLES
+#			# Redirect all the foreign tables to xxxxxx_test by changing the dbname of the "foreign server"
+#			# Also remove the host so the connection are fast linux socket connections instead of tcp/ip
+#			FOREIGN_TEST_DBNAME=${FOREIGN_SERVER}_test
+#			if ! sudo -u postgres psql $TEST_EXO_DATA -t -c "ALTER SERVER $FOREIGN_SERVER OPTIONS (SET host '', SET dbname '$FOREIGN_TEST_DBNAME');"; then
+#				: "ERROR: Problem changing foreign database to $FOREIGN_TEST_DBNAME"
+#				exit 1
+#			fi
+#			#batesk_test=> \des+
+#			#                                                         List of foreign servers
+#			#  Name  | Owner  | Foreign-data wrapper | Access privileges | Type | Version |                 FDW options                  | Description 
+#			#--------+--------+----------------------+-------------------+------+---------+----------------------------------------------+-------------
+#			# batesd | exodus | postgres_fdw         |                   |      |         | (dbname 'batesd_test', host '', port '5432') | 
 #
-#			#Print proof
-#			EXO_DATA=$TEST_EXO_DATA dbattach \{L\}
-#			sudo -u postgres psql -c "ALTER ROLE exodus WITH NOSUPERUSER;"
-		fi
-	fi
+##			#Get foreign table names before detaching
+##			FOREIGN_TABLES=`sudo -u postgres psql $TEST_EXO_DATA -t \
+##				-c "SELECT foreign_table_name FROM information_schema.foreign_tables;" \
+##				| tr '\n' ' '`
+##
+##			sudo -u postgres psql -c "ALTER ROLE exodus WITH SUPERUSER;"
+##			#Remove foreign server/tables attachment to other live database:
+##			EXO_DATA=$TEST_EXO_DATA dbattach \{RRR\}
+##
+##			#Reattach to other TEST database
+##			TIMEOUT=3600
+##			ELAPSED=0
+##			#Wait until source test database is finished being restore before dbattaching target/source test databases
+##			#otherwise dbcomp will fail because source db data not complete
+##			while ps -ef | egrep "backup_db $FOREIGN_SERVER" | grep -v 'grep'; do
+##				:
+##				: "Waiting for "$FOREIGN_SERVER"'s backup_db to finish before reattaching to "${FOREIGN_SERVER}_test
+##				:
+##				if [ $ELAPSED -ge $TIMEOUT ]; then
+##					: "TIMEOUT (60mins)"
+##					exit 1
+##				fi
+##				ELAPSED=$((ELAPSED + 60))
+##				sleep 60
+##			done
+##
+##			#Reattach to source's TEST database
+##			EXO_DATA=$TEST_EXO_DATA dbattach ${FOREIGN_SERVER}_test $FOREIGN_TABLES
+##
+##			#Print proof
+##			EXO_DATA=$TEST_EXO_DATA dbattach \{L\}
+##			sudo -u postgres psql -c "ALTER ROLE exodus WITH NOSUPERUSER;"
+#		fi
+#	fi
 :
 : Repopulate pg_statistic to avoid unnecessary aggressive autovacuum, send it to background
 : ─────────────────────────────────────────────────────────────────────────────────
